name: CI

on: [push]

jobs:
  run-unit-tests:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run Prettier (Check)
      run: yarn prettier-check

    - name: Run Jest
      run: yarn test --coverage --runInBand
